#!/usr/bin/perl
# Crappy DBM::Deep client
# A low-class hooker: not pretty, just does the job and gets out of the way
# James Stanley 2013

use strict;
use warnings;

use Data::Dump qw(dump);
use DBM::Deep;

my $PROMPT = 'perl> ';

my $usage = 'usage: dbmdc FILENAME';
my $file = shift or die "$usage\n";

my $db = DBM::Deep->new($file);

print STDERR "Your database is called \$db\n";
print STDERR "Interact with it using normal Perl.\n";
print STDERR "The result of each line is dumped to stdout.\n";
print STDERR "\n";

while (1) {
    print STDERR $PROMPT;
    my $line = <>;
    last if !defined $line;
    chomp $line;

    my $result = eval "$line";
    print STDERR $@ if $@;
    print dump($result), "\n" if !$@;
}
